export const actionsEnums = {
  UPDATE_USERPROFILE_NAME : 'UPDATE_USERPROFILE_NAME ',
  UPDATE_USERPROFILE_FAVOURITE_COLOR: 'UPDATE_USERPROFILE_FAVOURITE_COLOR',
  MEMBER_REQUEST_COMPLETED: 'MEMBER_REQUEST_COMPLETED',
  USER_CREATE_COMPLETED:'USER_CREATE_COMPLETED',
  USER_LOGIN_COMPLETED:'USER_LOGIN_COMPLETED',
  CHANGE_LOGIN:'CHANGE_LOGIN',
  CHANGE_PASSWORD:'CHANGE_PASSWORD'
}
